search_space:
  stages: [1, 2, 3, 4]
  conv_types: ["DWSepConv", "MBConv", "DpConv", "SeSepConv", "SeDpConv"]
  kernel_sizes: [3, 5, 7]
  strides: [1, 2, 4]
  skip_connection: [True, False]
  activations: ["ReLU6", "LeakyReLU", "Swish"]
  expansions: [1, 2, 3, 4]
  channels: [8, 16, 24, 32]
  has_se: [True, False]
  se_ratios: [0, 0.25, 0.5]
  blocks_per_stage: [1, 2]
  quantization_modes: ["none", "static", "qat"]  # 新增量化选项
  
constraints:
  max_peak_memory: 20e6
  max_latency: 5000  # 单位为毫秒